# Generated by Django 3.2 on 2021-04-28 13:59

from django.db import migrations, models
import django.db.models.deletion
import novels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('running_time', models.CharField(blank=True, max_length=5, null=True)),
                ('release_date', models.CharField(blank=True, max_length=4, null=True)),
                ('bitrate', models.CharField(blank=True, max_length=4, null=True)),
                ('links', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorAudiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cover', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.ImageField(upload_to=novels.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='MainCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('name_story_eng', models.CharField(max_length=100)),
                ('name_story_rus', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('slug', models.SlugField()),
                ('year', models.CharField(max_length=4)),
                ('title_eng', models.CharField(max_length=100)),
                ('title_rus', models.CharField(max_length=100)),
                ('alternative_title_eng_1', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_eng_2', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_eng_3', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_1', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_2', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_3', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_4', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_5', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_6', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_7', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_8', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_9', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_10', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_title_rus_11', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('books_rus_epub', models.FileField(blank=True, null=True, upload_to='novels/books/books_rus_epub')),
                ('books_rus_fb2', models.FileField(blank=True, null=True, upload_to='novels/books/books_rus_fb2')),
                ('books_rus_pdf', models.FileField(blank=True, null=True, upload_to='novels/books/books_rus_pdf')),
                ('books_rus_djvu', models.FileField(blank=True, null=True, upload_to='novels/books/books_rus_djvu')),
                ('books_eng_epub', models.FileField(blank=True, null=True, upload_to='novels/books/books_eng_epub')),
                ('books_eng_pdf', models.FileField(blank=True, null=True, upload_to='novels/books/books_eng_pdf')),
                ('books_eng_djvu', models.FileField(blank=True, null=True, upload_to='novels/books/books_eng_djvu')),
                ('books_fr_epub', models.FileField(blank=True, null=True, upload_to='novels/books/books_fr_epub')),
                ('books_fr_pdf', models.FileField(blank=True, null=True, upload_to='novels/books/books_fr_pdf')),
                ('books_it_pdf', models.FileField(blank=True, null=True, upload_to='novels/books/books_it_pdf')),
                ('novel_txt', models.FileField(blank=True, null=True, upload_to='novels/books/books_rus_txt')),
                ('audiobooks', models.ManyToManyField(blank=True, to='novels.Audiobook')),
                ('book_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.bookgenre')),
                ('covers', models.ManyToManyField(blank=True, to='novels.Cover')),
                ('main_characters', models.ManyToManyField(blank=True, to='novels.MainCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rus', models.CharField(blank=True, max_length=100, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.CharField(blank=True, max_length=4, null=True)),
                ('running_time', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.URLField(blank=True)),
                ('film_cover', models.ImageField(blank=True, null=True, upload_to=novels.models.film_cover_upload)),
                ('according_to_the_novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
            ],
        ),
        migrations.AddField(
            model_name='audiobook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.authoraudiobook'),
        ),
    ]
